//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestTxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsList
    {
        public int ID { get; set; }
        public Nullable<int> saveID { get; set; }
        public Nullable<int> itemID { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Saves Saves { get; set; }
    }
}
