//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestTxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Levels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Levels()
        {
            this.Riddles1 = new HashSet<Riddles>();
            this.Saves = new HashSet<Saves>();
        }
    
        public int LevelID { get; set; }
        public string textOFLevel { get; set; }
        public Nullable<int> FirstOptionID { get; set; }
        public Nullable<int> SecondOptionID { get; set; }
        public Nullable<int> ThirdOptionID { get; set; }
        public Nullable<int> riddleID { get; set; }
        public Nullable<bool> isEnd { get; set; }
        public Nullable<int> giveItemID { get; set; }
    
        public virtual Options Options { get; set; }
        public virtual Options Options1 { get; set; }
        public virtual Options Options2 { get; set; }
        public virtual Riddles Riddles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Riddles> Riddles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Saves> Saves { get; set; }
    }
}
