//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestTxt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestTxtEntities2 : DbContext
    {
        public QuestTxtEntities2()
            : base("name=QuestTxtEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemsList> ItemsList { get; set; }
        public virtual DbSet<Levels> Levels { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Riddles> Riddles { get; set; }
        public virtual DbSet<Saves> Saves { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
