//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestTxt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Saves()
        {
            this.ItemsList = new HashSet<ItemsList>();
        }
    
        public int Save_ID { get; set; }
        public Nullable<bool> isCurrentSave { get; set; }
        public Nullable<int> currentLevel { get; set; }
        public Nullable<int> itemsListID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsList> ItemsList { get; set; }
        public virtual Levels Levels { get; set; }
    }
}
